### ISSUE TITLE
Add: Automoderation function

### ISSUE THREAD

**Issue by z404** [ACM-VIT/golly-bot#11]
Create a command that deletes any message that contains the word "Voldemort", and sends the message "Shh we aren't supposed to speak that name!" in the same channel the message was sent. (Make sure the bot you're using to test has relevant permissions to delete messages in channels)

**Comment by MqllR** [comment]
Hi @z404,

I looked at the Auto moderation feature. My main concern here is that the GuildID become mandatory as the rule creation requires it. And because this feature is a bit specific (some server settings to enable AutoMod, scope...) compare to the others, are you ok to have a special flag in order to enable this for the app ?

Something like `--enable-automod`

And you can assign it to me btw, thanks ! :pray:

**Comment by z404** [comment]
Hi @MqllR,

Thanks for showing interest in this issue. Yeah, I think this could work perfectly, adding a flag is fine. I'll assign this issue to you, and if you have any more questions, feel free to discuss them here :D
